# Change these first
owner: DWARF57 # Your GitHub organization or username, where this repository lives
repo: Game4Cloud-Status # The name of this repository

sites:
  - name: Game4Cloud Homepage
    url: https://game4.cloud/
  - name: Game4Cloud Gamepanel
    url: https://panel.game4.cloud/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /game4cloud-status
  logoUrl: https://game4.cloud/templates/lagom2/assets/img/favicons/favicon.ico
  name: Game4Cloud - Server Status
  introTitle: ""
  introMessage:
  navbar:


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
