# Change these first
owner: DWARF57 # Your GitHub organization or username, where this repository lives
repo: Game4Cloud-Status # The name of this repository

sites:
  - name: Game4Cloud Homepage
    url: https://game4.cloud/
  - name: Game4Cloud Gamepanel
    url: https://panel.game4.cloud/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /game4cloud-status
  logoUrl: https://game4.cloud/templates/lagom2/assets/img/logo/logo_big.176418523.svg
  favicon: https://game4.cloud/templates/lagom2/assets/img/favicons/favicon-16.png
  name: Game4Cloud - Server Status
  theme: dark
  introTitle: "Game4Cloud Server Status"
  introMessage: hello, nice to see you
  navbar:
    - title: Game4Cloud
      href: https://game4.cloud/


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
